apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-kafka-producer
spec:
  selector:
    matchLabels:
      app: simple-kafka-producer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: simple-kafka-producer
    spec:
      containers:
      - name: simple-kafka-producer
        image: cwza/simple_kafka:latest
        imagePullPolicy: Always
        command: ["/producer"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "60m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ADDRESS
          value: {{ .Values.address }}
        - name: TOPIC
          value: {{ .Values.topic }}
        - name: PARTITION
          value: {{ .Values.partition }}
        - name: INTERVAL
          value: {{ .Values.producer.interval }}